service: step-functions

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  stackTags:
    product: datateam
    env: qa
    created-date: 2022-03-16
    team: data
    customer-impact: false
    terraform: false


functions:
  step1:
    handler: handler.step_1
  step2:
    handler: handler.step_2
  errorstate:
    handler: handler.error_state

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters


stepFunctions:
  stateMachines:
    hellostepfunc2:
      definition:
        StartAt: FirstTask
        States:
          FirstTask:
            Type: Task
            Resource:
              Fn::GetAtt: [step1, Arn]
            Retry:
              - ErrorEquals:
                  - States.TaskFailed
                IntervalSeconds: 30
                MaxAttempts: 2
                BackoffRate: 2
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 5
                MaxAttempts: 5
                BackoffRate: 2
            Catch:
              - ErrorEquals: ["States.TaskFailed"]
                Next: ErrorTask
              - ErrorEquals: ["States.ALL"]
                Next: ErrorTask
            Next: SecondTask
          SecondTask:
            Type: Task
            Resource:
              Fn::GetAtt: [step2, Arn]
            End: true
          ErrorTask:
            Type: Task
            Resource:
              Fn::GetAtt: [errorstate, Arn]
            End: true


